name: Generate Documentation with DocFx

on:
  push:
    branches:
      - main  # Replace with your desired branch name
  pull_request:
    branches:
      - main  # Replace with your desired branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.302'  # Replace with the desired .NET version

    - name: Install DocFx
      run: dotnet tool update -g docfx

    - name: Build and Generate Documentation
      run: cd docfx_project; docfx

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Replace with the path to your generated documentation

